name          'waveclaw-sickbeard'
version       '0.1.0'
source        'https://github.com/midgetspy/Sick-Beard/'
author        'waveclaw'
license       'Apache 2.0'
summary       'Sickbeard searches for Television programs on Usenet.'
description   ''
project_page  'https://gitbhub.com/waveclaw/puppet-sickbeard/'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/apt'
dependency 'darin/zypprepo', '>= 1.0.2'
